spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_platform?useSSL=false
    username: root
    password: Root

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect